###
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "name": "Casaco feminino",
  "categoryId": "92b00b80-1624-11f0-97c1-6242c8e67743",
  "image": "http://test.com",
  "price": 54.44,
  "description": "Casaco para neve"
}

###
GET http://localhost:8080/api/v1/products
Content-Type: application/json

###
GET http://localhost:8080/api/v1/products/b5f9a6d4-1654-11f0-8dc5-6242c8e67743
Content-Type: application/json
